
#變數
variables:
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm
  - name: vm_front_dist_path
    value: '~/www/pingtung/frontend-front-dist'

#監控的Git分支(可一個或多個)
trigger:
  - master
#建置環境(可設定 Windows、Linux 或是 macOS)，預設ubuntu-latest
pool:
  vmImage: ubuntu-latest
#階段
stages:
  - stage: Build
    displayName: Build stage
  - stage: Deploy
    displayName: Deploy stage
