# 流程: 
# stages > jobs > steps [ script | bash | pwsh | powershell | checkout | task | templateReference ]

# 監控的Git分支(可一個或多個)
trigger:
  - master
# 建置環境(可設定 Windows、Linux 或是 macOS)，預設ubuntu-latest
pool:
  vmImage: ubuntu-latest
# 階段
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: 環境配置
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 20.10.0
            displayName: Install Node.js
          - script: |
              npm i -g pnpm
              pnpm i -no-frozen-lockfile  
            displayName: Install pnpm
          - script: |
              pnpm build
            displayName: vite build project
          - task: CopyFiles@2
            inputs:
              SourceFolder: vue-vite-demo/dist
              TargetFolder: $(Build.SourcesDirectory)/vue-vite-demo-dist
              OverWrite: true
            displayName: Copy build dist folder  
          - script: | 
              git add .
              git commit -m "[Pipeline] $(Build.SourceVersionMessage)"
              git push
            workingDirectory: vue-vite-demo-dist
            displayName: git dist copy success
  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - job: deploy
        displayName: 佈署vue application
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist'
          - script: |
             echo deploy done !
            displayName: 佈署完成

      
            
              
    
