# 流程: 
# stages > jobs > steps [ script | bash | pwsh | powershell | checkout | task | templateReference ]
# 監控的Git分支(可一個或多個)
trigger:
  - master
# 建置環境(可設定 Windows、Linux 或是 macOS)，預設ubuntu-latest
pool:
  vmImage: ubuntu-latest
# 階段(包含多個jobs)
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    # 工作(包含多個steps)
      - job: Build
        displayName: 環境配置
        steps:
          # self:目前存放庫已取出
          - checkout: self 
            displayName: git clone

          - task: NodeTool@0
            inputs:
              versionSpec: 20.10.0
            displayName: Install Node.js

          - script: |
              npm i -g pnpm
              pnpm i -no-frozen-lockfile
            workingDirectory: vue-vite-demo    
            displayName: pnpm install

          - checkout: git://Vue3-Vite/vue-vite-demo-dist
            persistCredentials: true
            displayName: gti checkout Dist repos

          - script: |
              git checkout main
            workingDirectory: vue-vite-demo-dist
            displayName: checkout to main

          - script: |
              pnpm build
            workingDirectory: vue-vite-demo  
            displayName: pnpm build
            
          - script: |
              echo $(System.DefaultWorkingDirectory) 
              echo $(buildPlatform)
            displayName: show 變數訊息

          - script: |
              echo $(Build.SourceVersionMessage)
            displayName: show push message

          - task: CopyFiles@2
            inputs:
              SourceFolder: vue-vite-demo/dist
              TargetFolder: $(Build.SourcesDirectory)/vue-vite-demo-dist
              OverWrite: true
            displayName: Copy build dist folder  

          - script: |
              git config user.email "beast964089@gmail.com"
              git config user.name "silence"
              git add .
              git commit -m "[Pipelines] $(Build.SourcesDirectory)"
              git push
            workingDirectory: vue-vite-demo-dist
            displayName: git dist push success
  # 更新 git          
  # - stage: Update
  #   displayName: Update git repos
  #   jobs:
  #     - job: Update
  #       displayName: 更新與推送 git
  #       steps:
  #          # self:目前存放庫已取出
  #         - checkout: self 
  #           displayName: git clone

  #         - checkout: git://Vue3-Vite/vue-demo
  #           persistCredentials: true
  #           displayName: 切換至 vue-demo repos
            
  #         - script: |
  #             git checkout main
  #           workingDirectory: vue-demo
  #           displayName: checkout to main

  #         - script: |
  #             git config user.email "beast964089@gmail.com"
  #             git config user.name "silence"
  #             git pull https://github.com/SlienceAn/vue-vite-demo.git --rebase
  #           workingDirectory: vue-demo 
  #           displayName: pull news to git repos  
  # 佈署          
  # - stage: Deploy
  #   displayName: Deploy Stage
  #   jobs:
  #     - job: deploy
  #       displayName: 佈署vue application
  #       steps:
  #         - task: PublishBuildArtifacts@1
  #           inputs:
  #             PathtoPublish: 'dist'
  #         - script: |
  #            echo deploy done !
  #           displayName: 佈署完成

      
            
              
    
