# 流程: 
# stages > jobs > steps [ script | bash | pwsh | powershell | checkout | task | templateReference ]

# 監控的Git分支(可一個或多個)
trigger:
  - master
# 建置環境(可設定 Windows、Linux 或是 macOS)，預設ubuntu-latest
pool:
  vmImage: ubuntu-latest
# 階段
stages:
  - stage: Build 
    jobs:
      - job: Build
        displayName: 環境配置
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 20.10.0
            displayName: Install Node.js
          - script: |
              npm i -g pnpm
              pnpm i -no-frozen-lockfile  
            displayName: Install pnpm
          - script: |
              pnpm build
            displayName: vite build project     
      
            
              
    
