/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IMaterialSymbolsApps: typeof import('~icons/material-symbols/apps')['default']
    IMaterialSymbolsBrowse: typeof import('~icons/material-symbols/browse')['default']
    IMaterialSymbolsCalendarViewMonth: typeof import('~icons/material-symbols/calendar-view-month')['default']
    IMaterialSymbolsCancel: typeof import('~icons/material-symbols/cancel')['default']
    IMaterialSymbolsCheckCircle: typeof import('~icons/material-symbols/check-circle')['default']
    IMaterialSymbolsDarkMode: typeof import('~icons/material-symbols/dark-mode')['default']
    IMaterialSymbolsGridOn: typeof import('~icons/material-symbols/grid-on')['default']
    IMaterialSymbolsGridView: typeof import('~icons/material-symbols/grid-view')['default']
    IMaterialSymbolsLogout: typeof import('~icons/material-symbols/logout')['default']
    IMaterialSymbolsMenuOpen: typeof import('~icons/material-symbols/menu-open')['default']
    IMaterialSymbolsPartlyCloudyDay: typeof import('~icons/material-symbols/partly-cloudy-day')['default']
    IMaterialSymbolsRainy: typeof import('~icons/material-symbols/rainy')['default']
    IMaterialSymbolsViewAgenda: typeof import('~icons/material-symbols/view-agenda')['default']
    IMaterialSymbolsWarning: typeof import('~icons/material-symbols/warning')['default']
    IMaterialSymbolsWbSunny: typeof import('~icons/material-symbols/wb-sunny')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
